/**
 * PrintingTracker REST API
 * Това REST API дефинира интерфейс за менажиране на база данни от клиенти, принтерите с които те разполагат, и броячи на използваните консумативи.  Този проект е част от дипломна защита на Мария Денкова и Иво Пеев в Технически Университет - София, катедра Компютърни Системи, випуск 2018. 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { CreatePricePackage } from '../model/createPricePackage';
import { PricePackage } from '../model/pricePackage';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class PricesService {

    protected basePath = 'http://localhost:8080';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param request 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createPrice(request: CreatePricePackage, observe?: 'body', reportProgress?: boolean): Observable<PricePackage>;
    public createPrice(request: CreatePricePackage, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PricePackage>>;
    public createPrice(request: CreatePricePackage, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PricePackage>>;
    public createPrice(request: CreatePricePackage, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (request === null || request === undefined) {
            throw new Error('Required parameter request was null or undefined when calling createPrice.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<PricePackage>(`${this.basePath}/api/v1/prices`,
            request,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param pricePackageId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deletePrice(pricePackageId: number, observe?: 'body', reportProgress?: boolean): Observable<PricePackage>;
    public deletePrice(pricePackageId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PricePackage>>;
    public deletePrice(pricePackageId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PricePackage>>;
    public deletePrice(pricePackageId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (pricePackageId === null || pricePackageId === undefined) {
            throw new Error('Required parameter pricePackageId was null or undefined when calling deletePrice.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.delete<PricePackage>(`${this.basePath}/api/v1/prices/${encodeURIComponent(String(pricePackageId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param pricePackageId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPrice(pricePackageId: number, observe?: 'body', reportProgress?: boolean): Observable<PricePackage>;
    public getPrice(pricePackageId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PricePackage>>;
    public getPrice(pricePackageId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PricePackage>>;
    public getPrice(pricePackageId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (pricePackageId === null || pricePackageId === undefined) {
            throw new Error('Required parameter pricePackageId was null or undefined when calling getPrice.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<PricePackage>(`${this.basePath}/api/v1/prices/${encodeURIComponent(String(pricePackageId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPrices(observe?: 'body', reportProgress?: boolean): Observable<Array<PricePackage>>;
    public getPrices(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<PricePackage>>>;
    public getPrices(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<PricePackage>>>;
    public getPrices(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<Array<PricePackage>>(`${this.basePath}/api/v1/prices`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param pricePackageId 
     * @param update 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updatePrice(pricePackageId: number, update: CreatePricePackage, observe?: 'body', reportProgress?: boolean): Observable<PricePackage>;
    public updatePrice(pricePackageId: number, update: CreatePricePackage, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<PricePackage>>;
    public updatePrice(pricePackageId: number, update: CreatePricePackage, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<PricePackage>>;
    public updatePrice(pricePackageId: number, update: CreatePricePackage, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (pricePackageId === null || pricePackageId === undefined) {
            throw new Error('Required parameter pricePackageId was null or undefined when calling updatePrice.');
        }
        if (update === null || update === undefined) {
            throw new Error('Required parameter update was null or undefined when calling updatePrice.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.put<PricePackage>(`${this.basePath}/api/v1/prices/${encodeURIComponent(String(pricePackageId))}`,
            update,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
